#name: tip-calculator

services:

  counter-app:
    image: 'node:26-trixie'
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - npm
      - run
      - dev
      - --
      - --host
      - 0.0.0.0
#    command:
#      - sleep
#      - infinity
    stdin_open: true
    tty: true
    ports:
      - "3200:3000"
    volumes:
      - './app:/app'
      - '../niteowl-ui:/app/packages/niteowl-ui'
      - '../niteowl-app-config:/app/packages/niteowl-app-config'
      - './firebase-admin.json:/run/secrets/firebase-admin.json:ro'
    env_file:
      - .env-counter-app
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/firebase-admin.json
    restart: unless-stopped
    networks: [niteowl-dev]

networks:
  niteowl-dev:
    name: niteowl-dev
    external: true
