/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as OrganizationSlugCounterSlugRouteImport } from './routes/$organizationSlug.$counterSlug'
import { Route as ApiCounterAvailableRouteImport } from './routes/api/counter.available'
import { Route as ApiCounterCommandRouteImport } from './routes/api/counter.command'
import { Route as ApiCounterStateRouteImport } from './routes/api/counter.state'
import { Route as ApiPushRouteImport } from './routes/api/push'
import { Route as ApiPushConfigRouteImport } from './routes/api/push.config'
import { Route as ApiPushTestRouteImport } from './routes/api/push.test'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationSlugCounterSlugRoute = OrganizationSlugCounterSlugRouteImport.update({
  id: '/$organizationSlug/$counterSlug',
  path: '/$organizationSlug/$counterSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCounterAvailableRoute = ApiCounterAvailableRouteImport.update({
  id: '/api/counter/available',
  path: '/api/counter/available',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCounterCommandRoute = ApiCounterCommandRouteImport.update({
  id: '/api/counter/command',
  path: '/api/counter/command',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCounterStateRoute = ApiCounterStateRouteImport.update({
  id: '/api/counter/state',
  path: '/api/counter/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushRoute = ApiPushRouteImport.update({
  id: '/api/push',
  path: '/api/push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushConfigRoute = ApiPushConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => ApiPushRoute,
} as any)
const ApiPushTestRoute = ApiPushTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => ApiPushRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/$organizationSlug/$counterSlug': typeof OrganizationSlugCounterSlugRoute
  '/api/counter/available': typeof ApiCounterAvailableRoute
  '/api/counter/command': typeof ApiCounterCommandRoute
  '/api/counter/state': typeof ApiCounterStateRoute
  '/api/push': typeof ApiPushRouteWithChildren
  '/api/push/config': typeof ApiPushConfigRoute
  '/api/push/test': typeof ApiPushTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/$organizationSlug/$counterSlug': typeof OrganizationSlugCounterSlugRoute
  '/api/counter/available': typeof ApiCounterAvailableRoute
  '/api/counter/command': typeof ApiCounterCommandRoute
  '/api/counter/state': typeof ApiCounterStateRoute
  '/api/push': typeof ApiPushRouteWithChildren
  '/api/push/config': typeof ApiPushConfigRoute
  '/api/push/test': typeof ApiPushTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/$organizationSlug/$counterSlug': typeof OrganizationSlugCounterSlugRoute
  '/api/counter/available': typeof ApiCounterAvailableRoute
  '/api/counter/command': typeof ApiCounterCommandRoute
  '/api/counter/state': typeof ApiCounterStateRoute
  '/api/push': typeof ApiPushRouteWithChildren
  '/api/push/config': typeof ApiPushConfigRoute
  '/api/push/test': typeof ApiPushTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assignments'
    | '/$organizationSlug/$counterSlug'
    | '/api/counter/available'
    | '/api/counter/command'
    | '/api/counter/state'
    | '/api/push'
    | '/api/push/config'
    | '/api/push/test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assignments'
    | '/$organizationSlug/$counterSlug'
    | '/api/counter/available'
    | '/api/counter/command'
    | '/api/counter/state'
    | '/api/push'
    | '/api/push/config'
    | '/api/push/test'
  id:
    | '__root__'
    | '/'
    | '/assignments'
    | '/$organizationSlug/$counterSlug'
    | '/api/counter/available'
    | '/api/counter/command'
    | '/api/counter/state'
    | '/api/push'
    | '/api/push/config'
    | '/api/push/test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssignmentsRoute: typeof AssignmentsRoute
  OrganizationSlugCounterSlugRoute: typeof OrganizationSlugCounterSlugRoute
  ApiCounterAvailableRoute: typeof ApiCounterAvailableRoute
  ApiCounterCommandRoute: typeof ApiCounterCommandRoute
  ApiCounterStateRoute: typeof ApiCounterStateRoute
  ApiPushRoute: typeof ApiPushRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$organizationSlug/$counterSlug': {
      id: '/$organizationSlug/$counterSlug'
      path: '/$organizationSlug/$counterSlug'
      fullPath: '/$organizationSlug/$counterSlug'
      preLoaderRoute: typeof OrganizationSlugCounterSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/counter/available': {
      id: '/api/counter/available'
      path: '/api/counter/available'
      fullPath: '/api/counter/available'
      preLoaderRoute: typeof ApiCounterAvailableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/counter/command': {
      id: '/api/counter/command'
      path: '/api/counter/command'
      fullPath: '/api/counter/command'
      preLoaderRoute: typeof ApiCounterCommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/counter/state': {
      id: '/api/counter/state'
      path: '/api/counter/state'
      fullPath: '/api/counter/state'
      preLoaderRoute: typeof ApiCounterStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push': {
      id: '/api/push'
      path: '/api/push'
      fullPath: '/api/push'
      preLoaderRoute: typeof ApiPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/config': {
      id: '/api/push/config'
      path: '/config'
      fullPath: '/api/push/config'
      preLoaderRoute: typeof ApiPushConfigRouteImport
      parentRoute: typeof ApiPushRoute
    }
    '/api/push/test': {
      id: '/api/push/test'
      path: '/test'
      fullPath: '/api/push/test'
      preLoaderRoute: typeof ApiPushTestRouteImport
      parentRoute: typeof ApiPushRoute
    }
  }
}

interface ApiPushRouteChildren {
  ApiPushConfigRoute: typeof ApiPushConfigRoute
  ApiPushTestRoute: typeof ApiPushTestRoute
}

const ApiPushRouteChildren: ApiPushRouteChildren = {
  ApiPushConfigRoute: ApiPushConfigRoute,
  ApiPushTestRoute: ApiPushTestRoute,
}

const ApiPushRouteWithChildren =
  ApiPushRoute._addFileChildren(ApiPushRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssignmentsRoute: AssignmentsRoute,
  OrganizationSlugCounterSlugRoute: OrganizationSlugCounterSlugRoute,
  ApiCounterAvailableRoute: ApiCounterAvailableRoute,
  ApiCounterCommandRoute: ApiCounterCommandRoute,
  ApiCounterStateRoute: ApiCounterStateRoute,
  ApiPushRoute: ApiPushRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
